name: Run Python Script

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - pr-raised

  #env:
    #PR_NUMBER: ${{ github.event.number }}

jobs:
  run-python-script:
    runs-on: self-hosted
    steps:
      - name: Get PR Number
        id: get-pr-number
        uses: mgaitan/gha-get-pr-number@v1

      - name: Run Python Script
        run: python test.py ${{ steps.get-pr-number.outputs.number }}
