name: Run Python Script

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - pr-raised

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: test.py
