name: Run Python Script

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - pr-raised

  #env:
    #PR_NUMBER: ${{ github.event.number }}

jobs:
  run-python-script:
    runs-on: self-hosted
    steps:
      - name: Run Python Script
        run: python test.py ${{github.event.number}}
