name: Run Python Script

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - pr-raised

  #env:
    #PR_NUMBER: ${{ github.event.number }}

jobs:
  run-python-script:
    runs-on: self-hosted
    steps:
      - name: Run Python Script for Review comment generation
        run: python /src/prompt_setup/review_comment_generation.py ${{ github.event.client_payload.pr_number }}